/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    articles: Article;
    "action-alerts": ActionAlert;
    pages: Page;
    media: Media;
  };
  globals: {
    "site-settings": SiteSettings;
  };
}

export interface User {
  id: string;
  email: string;
  name?: string | null;
  role: "admin" | "editor" | "viewer";
  avatar?: string | Media | null;
  updatedAt: string;
  createdAt: string;
}

export interface Article {
  id: string;
  title: string;
  slug: string;
  author: string | User;
  category:
    | "immigration"
    | "environment"
    | "healthcare"
    | "education"
    | "civil_rights"
    | "labor"
    | "economy"
    | "defense"
    | "justice"
    | "government"
    | "general";
  featuredImage?: string | Media | null;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedObjectiveIds?: unknown | null;
  status: "draft" | "published" | "archived";
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: string | Media | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface ActionAlert {
  id: string;
  title: string;
  urgency: "critical" | "high" | "medium";
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  callToAction: {
    text: string;
    url: string;
  };
  relatedObjectiveIds?: unknown | null;
  displayLocations?: ("homepage" | "tracker" | "category")[] | null;
  active?: boolean | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface Page {
  id: string;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: "draft" | "published";
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}

export interface SiteSettings {
  id: string;
  siteTitle: string;
  tagline?: string | null;
  threatLevel?: {
    level?: ("critical" | "high" | "elevated" | "moderate") | null;
    autoCalculate?: boolean | null;
    manualOverrideReason?: string | null;
  };
  featuredObjectiveIds?: unknown | null;
  navigation?:
    | {
        label: string;
        url: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    copyrightText?: string | null;
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
